name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --dry-run > output.log 2>&1

          V=$(grep "The next release version is" output.log | tail -1 | awk '{print $NF}')
          echo "Next version: $V"

          if [ -n "$V" ]; then
            npm version "$V" --no-git-tag-version

            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package*.json
            git commit -m "v$V [skip ci]" -m "Co-authored-by: Fauzira Alpiandi <fwzyrln@gmail.com>"
            git push origin HEAD:main
          fi

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
